alias: null
batch_size: 32
cell_type: LSTM
context_size: 10
decoder_hidden_size: 200
decoder_layers: 2
dilations:
- - 1
  - 2
- - 4
  - 8
drop_last_loader: false
early_stop_patience_steps: -1
encoder_hidden_size: 200
futr_exog_list: null
h: 5
hist_exog_list:
- mean_future
- mean_influential
- mean_trustworthy
- mean_clickbait
- norm_rsi_14
- norm_rsi_gspc_14
- norm_slowk_14
inference_input_size: -1
input_size: 10
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.RMSE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
max_steps: 10
num_lr_decays: 3
num_workers_loader: 0
random_seed: 1
scaler_type: standard
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: null
