MovingAvg_window: 25
activation: gelu
alias: null
batch_size: 32
conv_hidden_size: 32
decoder_input_size_multiplier: 0.5
decoder_layers: 1
drop_last_loader: false
dropout: 0.05
early_stop_patience_steps: -1
encoder_layers: 2
exclude_insample_y: false
futr_exog_list:
- mean_future
- mean_influential
- mean_trustworthy
- mean_clickbait
- log_return_gspc_1
- norm_rsi_14
- norm_slowk_14
- norm_roc_14
h: 10
hidden_size: 128
hist_exog_list: null
inference_windows_batch_size: 1024
input_size: 3
learning_rate: 0.00018267955548970072
loss: !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
max_steps: 100
mode_select: random
modes: 64
n_head: 8
num_lr_decays: -1
num_workers_loader: 0
random_seed: 1
scaler_type: standard
start_padding_enabled: false
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: null
version: Fourier
windows_batch_size: 1024
