activation: ReLU
alias: null
batch_size: 32
drop_last_loader: false
dropout_prob_theta: 0.0
early_stop_patience_steps: -1
exclude_insample_y: false
futr_exog_list: null
h: 5
hist_exog_list:
- finbert_Score
- bart_Score
- vader_Score
- mean_influential
- mean_trustworthy
- norm_rsi_gspc_14
- norm_rsi_14
- norm_slowk_14
- minmax_high_norm
- log_return_1
inference_windows_batch_size: -1
input_size: 10
learning_rate: 0.002134323079727657
loss: !!python/object:neuralforecast.losses.pytorch.MQLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - quantiles
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDQAAADI2MjE3OTkxMzAxNzZxAlgDAAAAY3B1cQNLBU50cQRRLoACXXEAWA0AAAAyNjIx
              Nzk5MTMwMTc2cQFhLgUAAAAAAAAAAAAAP83MTD3NzMw9ZmZmPzMzcz8=
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADgAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADgAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAAwAAAA
  outputsize_multiplier: 5
  training: true
max_steps: 1
mlp_units:
- - 32
  - 32
n_blocks:
- 3
- 1
- 1
n_harmonics: 2
n_polynomials: 4
num_lr_decays: 3
num_workers_loader: 0
random_seed: 1
scaler_type: standard
shared_weights: false
stack_types:
- seasonality
- trend
- identity
start_padding_enabled: false
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: null
windows_batch_size: 1024
