options:
  currency:
    - BA
    - BTCUSD
    - NFLX
    - TSLA
  time_period:
    - 1
    - 5
    - 10
api_keys:
  alphavantage:
    - NQQYUFL94Q5M3YH2
  marketaux:
    - VhQlodkXbHbZE0vUS6eQhYwdSvfgQSP4NjLrVACo
    - B12FwLhv80TqecMLNRdaiMIZiTPOKzhxMY2tLwWY
    - m0Q3p7snIwLxxVueQjY2QkORIUKvMrDB4CLy7xi8
    - 65tlBN9OAjlbR2EGMOb97BnTtf1axhOUw8YFSiZZ
    - 6IGEFIcvpdJiSdmTH99BSn8AVfftuOnHAwI8vkZX
    - 07O7pQpMO2hruWQmU6S8LJncJrD9tYoQEa94mjL7
    - 7jpIvaNVSfbzKgSjBJUjKLGOkheDqlXXHow0hqV2
    - ru9csB3TBwCjpfyUzw4f3hE2vB88y8iiER0dpXj3
    - egwiukhKomAbje2lrrKL1z1ECN8ienRm6aBd5Wsp
    - 9oxxLUTAiMSXceql18HZ4Xz1CKhwa2bVtEMuqIAQ
    - UuxWMNP8XfDuppbNinpvBYOfedJouSYMEwjEUwOq
    - gk0849Cv6DTfsMAmzp13qp7Q09ULfgnNWHd8R3LS
    - TEDETqt2eka8HbEXr9iHafaQaaC8yntxJ4kqg5DV
    - 1A6BIomNHkYfwuVEXkS06zz2CmVRtOYKy451cj8k
    - DklBEXK6POj73EGZuTAYMN9EEHBLMWe9Flgenz0P
    - TXIDyS8bYmUYUXLkSZIJ27HMPn4G1XrjxmgRONYk
    - d01yoYY7lebNcRsFB4jLWLJoYsO1ANSay1frZeCc
    - FOlRHekaaKXDO8OzQCm3OhFXcn9AN87InF6poZye
    - SbVF63j1kq1oLd8xLrXb1c9NePopE78XlqukJLlR 
    - n7Z3u8RoupEccoFTSilWh9S8XpTvFVJidSZS7rfR
    - hDxiXlgvgd5SBo0zzSWVYIJdnFk4r7Bfjc4N62du
    - VXaKyxfn2nFD0SXV7wmW1BB9eagIdhw47plxumag
    - mRmoOIAtcd862pkbbON8eospdaKlyN6i0GQikHXa
    - fhTKQOtkv136elD1O4wE87giBKHJKjrOzoLiGuzv
    - RspkY5dUGKD16wDJytHjHNv6sVbRTulvcyugRDYU
    - SnzD2thuyDWGZ4dg5OOKzRTIS1rAFhXY2Hzd1xjH
    - rRIg0OrTma5LQR9a4zF37clVAAyUB9ZUaAupdJgL